from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1125, 705)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(400, 10, 351, 61))
        self.label.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(170, 0, 127);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 120, 351, 61))
        self.label_2.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(170, 0, 127);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 240, 401, 61))
        self.label_3.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(170, 0, 127);")
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(600, 120, 391, 71))
        self.lineEdit.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(600, 240, 391, 71))
        self.lineEdit_2.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(600, 360, 391, 71))
        self.lineEdit_3.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 360, 401, 61))
        self.label_4.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(170, 0, 127);")
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(190, 510, 111, 91))
        self.pushButton.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(380, 510, 111, 91))
        self.pushButton_2.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(560, 510, 111, 91))
        self.pushButton_3.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(740, 510, 111, 91))
        self.pushButton_4.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1121, 671))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(170, 20, 651, 91))
        self.lineEdit_4.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(70, 150, 111, 81))
        self.pushButton_5.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setGeometry(QtCore.QRect(280, 150, 111, 81))
        self.pushButton_6.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setGeometry(QtCore.QRect(500, 150, 111, 81))
        self.pushButton_7.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8.setGeometry(QtCore.QRect(70, 270, 111, 81))
        self.pushButton_8.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame)
        self.pushButton_9.setGeometry(QtCore.QRect(500, 270, 111, 81))
        self.pushButton_9.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame)
        self.pushButton_10.setGeometry(QtCore.QRect(280, 270, 111, 81))
        self.pushButton_10.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame)
        self.pushButton_11.setGeometry(QtCore.QRect(70, 400, 111, 81))
        self.pushButton_11.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame)
        self.pushButton_12.setGeometry(QtCore.QRect(500, 400, 111, 81))
        self.pushButton_12.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.frame)
        self.pushButton_13.setGeometry(QtCore.QRect(280, 400, 111, 81))
        self.pushButton_13.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_23 = QtWidgets.QPushButton(self.frame)
        self.pushButton_23.setGeometry(QtCore.QRect(70, 520, 111, 81))
        self.pushButton_23.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.frame)
        self.pushButton_24.setGeometry(QtCore.QRect(280, 520, 111, 81))
        self.pushButton_24.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(self.frame)
        self.pushButton_25.setGeometry(QtCore.QRect(500, 520, 111, 81))
        self.pushButton_25.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtWidgets.QPushButton(self.frame)
        self.pushButton_26.setGeometry(QtCore.QRect(860, 270, 111, 81))
        self.pushButton_26.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_27 = QtWidgets.QPushButton(self.frame)
        self.pushButton_27.setGeometry(QtCore.QRect(860, 150, 111, 81))
        self.pushButton_27.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(self.frame)
        self.pushButton_28.setGeometry(QtCore.QRect(860, 520, 111, 81))
        self.pushButton_28.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_29 = QtWidgets.QPushButton(self.frame)
        self.pushButton_29.setGeometry(QtCore.QRect(860, 400, 111, 81))
        self.pushButton_29.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_30 = QtWidgets.QPushButton(self.frame)
        self.pushButton_30.setGeometry(QtCore.QRect(650, 190, 181, 81))
        self.pushButton_30.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_31 = QtWidgets.QPushButton(self.frame)
        self.pushButton_31.setGeometry(QtCore.QRect(650, 320, 181, 81))
        self.pushButton_31.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_32 = QtWidgets.QPushButton(self.frame)
        self.pushButton_32.setGeometry(QtCore.QRect(650, 460, 181, 81))
        self.pushButton_32.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_32.setObjectName("pushButton_32")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1125, 31))
        self.menubar.setObjectName("menubar")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionBasic = QtWidgets.QAction(MainWindow)
        self.actionBasic.setObjectName("actionBasic")
        self.actionScientific = QtWidgets.QAction(MainWindow)
        self.actionScientific.setObjectName("actionScientific")
        self.menuOptions.addAction(self.actionBasic)
        self.menuOptions.addAction(self.actionScientific)
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Basic Calculator"))
        self.label_2.setText(_translate("MainWindow", "Enter first number"))
        self.label_3.setText(_translate("MainWindow", "Enter second number"))
        self.label_4.setText(_translate("MainWindow", "Result"))
        self.pushButton.setText(_translate("MainWindow", "+"))
        self.pushButton_2.setText(_translate("MainWindow", "-"))
        self.pushButton_3.setText(_translate("MainWindow", "/"))
        self.pushButton_4.setText(_translate("MainWindow", "*"))
        self.pushButton_5.setText(_translate("MainWindow", "7"))
        self.pushButton_6.setText(_translate("MainWindow", "8"))
        self.pushButton_7.setText(_translate("MainWindow", "9"))
        self.pushButton_8.setText(_translate("MainWindow", "4"))
        self.pushButton_9.setText(_translate("MainWindow", "6"))
        self.pushButton_10.setText(_translate("MainWindow", "5"))
        self.pushButton_11.setText(_translate("MainWindow", "1"))
        self.pushButton_12.setText(_translate("MainWindow", "3"))
        self.pushButton_13.setText(_translate("MainWindow", "2"))
        self.pushButton_23.setText(_translate("MainWindow", "."))
        self.pushButton_24.setText(_translate("MainWindow", "0"))
        self.pushButton_25.setText(_translate("MainWindow", "?"))
        self.pushButton_26.setText(_translate("MainWindow", "-"))
        self.pushButton_27.setText(_translate("MainWindow", "+"))
        self.pushButton_28.setText(_translate("MainWindow", "*"))
        self.pushButton_29.setText(_translate("MainWindow", "/"))
        self.pushButton_30.setText(_translate("MainWindow", "C"))
        self.pushButton_31.setText(_translate("MainWindow", "<-"))
        self.pushButton_32.setText(_translate("MainWindow", "="))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.actionBasic.setText(_translate("MainWindow", "Basic"))
        self.actionScientific.setText(_translate("MainWindow", "Advance Calc"))

        self.frame.hide()
        self.lineEdit_3.setReadOnly(True)

        # self.pushButton.clicked.connect(self.add)
        buttons = [self.pushButton,self.pushButton_2,self.pushButton_3,self.pushButton_4]
        for i in range(len(buttons)):
            buttons[i].clicked.connect(self.calc)

        self.actionScientific.triggered.connect(self.showAdvCalc)
        self.actionBasic.triggered.connect(self.showHome)

    def showHome(self):
        self.frame.hide()

    def showAdvCalc(self):
        self.frame.show()
    # def add(self):
    #     try:
    #         f_num = int(self.lineEdit.text())
    #         s_num = int(self.lineEdit_2.text())
    #         result = f_num + s_num
    #         self.lineEdit_3.setText(str(result))
    #     except BaseException as ex:
    #         print(ex)

    def calc(self):
        btn = self.sender()
        opr = btn.text()
        f_num = self.lineEdit.text()
        s_num = self.lineEdit_2.text()
        expression = f_num + opr + s_num
        result = eval(expression)
        self.lineEdit_3.setText(str(result))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
